services:

    database:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: 'GreenHubDB'
            MYSQL_USER: 'Math'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        volumes:
            - 'greenhubdb:/var/lib/mysql'
        ports:
            - '3307:3306'

    app:
        image: backend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8181:8181"
        environment:
            DB_CONNECTION: "mysql"
            DB_HOST: "database"
            DB_PORT: "3306"
            DB_DATABASE: "GreenHubDB"
            DB_USERNAME: "Math"
            DB_PASSWORD: "password"
volumes:
    greenhubdb:


